### ISSUE TITLE
dropbox login page few seconds automatically close 

### ISSUE THREAD

**Issue by chicly** [dropbox/dropbox-sdk-dotnet#100]
var login = new DropboxLogin
        (
          clientId: "kzcgsmbxkxuyur2",
          clientSecret: "REDACTED",
          returnUrl: "https://localhost/authorize",
          autoLogout: true,
          loadUserInfo: false
        )
        { Owner = this };
        login.ShowDialog();

        if (login.IsSuccessfully)
        {
            MessageBox.Show(login.AccessToken.Value);
        }
        else
        {
            MessageBox.Show("Error............");
            this.Close();
        }

**Comment by greg-db** [comment]
Based on your code, it looks like you're actually using a third party library [Nemiro.OAuth.LoginForms](https://github.com/alekseynemiro/Nemiro.OAuth.LoginForms), not [this official one](https://github.com/dropbox/dropbox-sdk-dotnet). 

That being the case, I'm afraid I can't offer help with this. You may want to open an issue for that library. (If you do find an issue with the Dropbox API itself, you can [report it here](https://www.dropbox.com/developers/contact).)
