### ISSUE TITLE
Add support for .NET core

### ISSUE THREAD

**Issue by mtycholaz** [dropbox/dropbox-sdk-dotnet#102]
Please add support for .NET Core 2.1

This would allow for development in Azure cloud functions (which currently only support .Net core runtime)

**Comment by greg-db** [comment]
The official Dropbox API v2 .NET SDK should already work on .NET Core 2.1. Have you tried installing it and run in to issues? If so, please share some more information so we can look into it:
- the steps to reproduce the issue
- the full text of any error or unexpected output
- the version numbers of the platform and development environment you're using

Please make sure you're using the latest version of the SDK first though.

**Comment by mtycholaz** [comment]
Thanks for the info. I'm trying to get a prototype running on dotnetcore, but I may have to abandon it because some other third-party SDK's don't support dotnetcore yet. I didn't get around to try the Dropbox SDK yet, but I had read the documentation and didn't see any mention of dotnetcore support. I'll take your word for it that it works though.

**Comment by Still34** [comment]
> Thanks for the info. I'm trying to get a prototype running on dotnetcore, but I may have to abandon it because some other third-party SDK's don't support dotnetcore yet. I didn't get around to try the Dropbox SDK yet, but I had read the documentation and didn't see any mention of dotnetcore support. I'll take your word for it that it works though.

Just an FYI, .NET Core introduced compatibility mode around 2.1 or 2.2, meaning most packages compiled with .NETFX should work unless the said package involves specific and ancient Windows APIs.
