### ISSUE TITLE
CreateFolderAync Obsolete, but replacement is also marked Obsolete?

### ISSUE THREAD

**Issue by tylerthardy** [dropbox/dropbox-sdk-dotnet#106]
**Version**:
Dropbox.Api (4.9.4)

**Description:**
The following methods are marked Obsolete, with a note to "use CreateFolderAync instead":
`Dropbox.Api.Files.Routes.FilesUserRoutes.CreateFolderAsync(string, bool)`
`Dropbox.Api.Files.Routes.FilesUserRoutes.CreateFolderAsync(CreateFolderArg)`
https://dropbox.github.io/dropbox-sdk-dotnet/html/Overload_Dropbox_Api_Files_Routes_FilesUserRoutes_CreateFolderAsync.htm
![image](https://user-images.githubusercontent.com/17709869/70383330-bb9de300-1931-11ea-934a-470d3b5c9faf.png)

**Issue:**
These are the only 2 methods with the name "CreateFolderAsync", and both are marked Obsolete. It's unclear what method should be used.

**Comment by greg-db** [comment]
Apologies for the confusion! It looks like the generated `Obselete` messages are referencing the wrong method name. I'll ask the team to fix that up.

In this case, it should be referencing [`CreateFolderV2Async`](https://dropbox.github.io/dropbox-sdk-dotnet/html/Overload_Dropbox_Api_Files_Routes_FilesUserRoutes_CreateFolderV2Async.htm).

**Comment by rogebrd** [comment]
This has been fixed and the new recommendation per the file: https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Dropbox.Api/Generated/Files/FilesUserRoutes.cs#L1339

Is to use BeginCreateFolder

**Comment by rogebrd** [comment]
My apologies, the link I was looking at ended up referencing itself, I can look into getting this fixed

**Comment by greg-db** [comment]
These deprecation warnings should be fixed now in the latest version.
