### ISSUE TITLE
search_v2 not supported?

### ISSUE THREAD

**Issue by PaulBol** [dropbox/dropbox-sdk-dotnet#109]
I figured out that `Dropbox.Api.DropboxClient.Files.SearchAsync` with parameters `path, query, start, maxResults, mode` maps to version 1 of the `/search` endpoint.

According to https://www.dropbox.com/developers/documentation/http/documentation this endpoint is **DEPRECATED BY version 2**. Version 2 also seems to be more powerful, e.g. search by file extension   (`file_extensions`).

How can I access the version 2 endpoint with the .NET SDK?

**Comment by greg-db** [comment]
The Dropbox .NET SDK does not yet implement the new /search_v2 endpoint. That should be added the next time the SDK is regenerated and released. I'll ask the team to do so, but I can't offer a timeline for that.

**Comment by PaulBol** [comment]
Thanks. Would be great to support the endpoint eventually. I noticed that some endpoints seem to be included already (e.g. `ListV2Async`).

**Comment by rogebrd** [comment]
SearchV2 is supported as of 5.0.0, closing for now, let me know if there is any other issues.

**Comment by PaulBol** [comment]
Thanks for the update. I confirmed that `SearchV2Async` works as expected.

Only the `Obsolete` attributes in FileUserRoutes,cs look wrong.

        [sys.Obsolete("This function is deprecated, please use BeginCreateFolder instead.")]
        public sys.IAsyncResult BeginCreateFolder(string path, ...

-> **BeginCreateFolder** is deprecated use **BeginCreateFolder** instead? Same for most of the following methods.

**Comment by greg-db** [comment]
@PaulBol Thanks for the note. You're correct, the generation of these deprecation warnings is currently broken. That's open with engineering to fix that up.
