### ISSUE TITLE
Folder whitespace error.

### ISSUE THREAD

**Issue by karlgjertsen** [dropbox/dropbox-sdk-dotnet#11]
After a lot of testing and trial and error, we have found that there is a bug if you include whitespace in the folder name, if you are creating the name dynamically.

We are saving to the Apps folder and used code similar to the following to set the folder and filename for the file.

```
var name = "/" + folder + "/" + filename;
dropbox.Files.UploadAsync(name, WriteMode.Overwrite.Instance, body: new MemoryStream(file));
```

This all worked from localhost, but when we deployed to Azure, the call stopped working.

We found that if 'folder' contains whitespace, the call fails.

1) name = "/" + "MyFolder + "/" + "Filename".
2) name = "/" + "My Folder + "/" + "Filename".

Number 1 worked, number 2 didn't.

If we hardcode the string, it allowed spaces. The following method call worked:

```
dropbox.Files.UploadAsync("/My Folder/file.pdf", WriteMode.Overwrite.Instance, body: new MemoryStream(file));
```

**Comment by qimingyuan** [comment]
Hi @kgjertsen 

I am not able to repro the failure locally. Could you please provide some additional information like exception or error messages?

**Comment by JimiC** [comment]
@kgjertsen Could it be an url encoding issues when deployed to Azure? Like whitespace gets encoded to %20?

**Comment by kgjertsen** [comment]
Hi,

Sorry for the delay in replying.

I'm not sure why this happens, but we have switched to using the Dropbox API.

Regards,

Karl

On 22 Jan 2016, at 21:05, Qiming Yuan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @kgjertsen<https://github.com/kgjertsen>

I am not able to repro the failure locally. Could you please provide some additional information like exception or error messages?

**Comment by rogebrd** [comment]
Closing as this does not seem to still be a relevant issue
