### ISSUE TITLE
oauth2 example 127.0.0.1 Access is denied

### ISSUE THREAD

**Issue by roblatour** [dropbox/dropbox-sdk-dotnet#110]
I am trying to run the SimpleTest .net example

In the code I have tried using:
private const string LoopbackHost = "http://localhost:52475/";
private const string LoopbackHost = "http://localhost:80/";
private const string LoopbackHost = "http://localhost/";
private const string LoopbackHost = "https://localhost/";
private const string LoopbackHost = "http://127.0.0.1/";
private const string LoopbackHost = "https://127.0.0.1";
and anything else I could think of.

But the best I can get is an "Assess is denied" after the http.start(); command

On my pc I can ping 127.0.0.1 no problem

also in the Dropbox app console, I have
http://localhost/
https://localhost/
http://127.0.0.1/
https://127.0.0.1/
all added as Redirect URIs

I am using visual studio 2019 with all packages updated.

Am I missing something or is this a bug

**Comment by greg-db** [comment]
I just tried the SimpleTest example app in Visual Studio 2019 with the default `LoopbackHost` value and I was able to run the listener and use the app authorization flow without issue.

Can you share more information on the error you're getting? Is it an exception being raised by `http.start`, for instance, or an error you're getting in the browser? If you can provide a stack trace or a screenshot/screencast showing the issue that may be helpful.

**Comment by roblatour** [comment]
yes, the exception is thrown after the http.start(); 
command and is being caught as an exception.

stacktrace:
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at SimpleTest.Program.<GetAccessToken>d__12.MoveNext() in C:\Users\Rob Latour\Desktop\dropbox sample\dropbox-sdk-dotnet-master\dropbox-sdk-dotnet\Examples\SimpleTest\Program.cs:line 235

Message:
Access is denied

The code has 
an apikey set to the value in the api console and 
private const string LoopbackHost = "http://127.0.0.1/";

Also, the dropbox app console has the following set:

Redirect URIs
http://localhost/
https://localhost/
http://127.0.0.1/
https://127.0.0.1/

**Comment by greg-db** [comment]
Thanks! Based on that stack trace though I see that this isn't actually failing in any Dropbox code, but rather in the `HttpListener` code itself. As that's not made by Dropbox, we can't offer too much help with that.

That said, it looks like this may depend on how your system is configured. There seems to be a similar issue here with some potential solutions: https://github.com/SignalR/SignalR/issues/3623

**Comment by roblatour** [comment]
Thanks - the linked post suggest running visual studio with admin privileges as a workaround.

I tried that, and got only a little further.

Running Visual Studio with admin privileges allows the sample program to open up my web browser (chrome), but I don't get a dropbox auth page, Instead I get a web page with an unhappy looking cat holding an umbrella with the following words underneath:

Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.


More details for developers
Invalid redirect_uri. It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

**Comment by greg-db** [comment]
That error indicates that your app does not currently have the specified redirect URI registered.

You should either switch to using a redirect URI that is already registered for your app, or register the current redirect URI for your app. You can add redirect URIs for your app on the app's page on [the App Console](https://www.dropbox.com/developers/apps), under the "OAuth 2" "Redirect URIs" section

**Comment by roblatour** [comment]
yes, but I do have it registered - as noted above.  The Redirect URIs under the "OAuth 2" "Redirect URIs" section are:
http://localhost/
https://localhost/
http://127.0.0.1/
https://127.0.0.1/

the url browser line reads:
https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=xxxxxxxxxxxxxxx&redirect_uri=http:%2F%2F127.0.0.1%2Fauthorize&state=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

where xxxx is my api key
and yyyy is a bunch of numbers and letters 

... am I missing something?

**Comment by roblatour** [comment]
I think I found the solution, or at least how to move things forward.

On the dropbox app console, I added the following redirect url
http://127.0.0.1/authorize
after that it seemed to work

**Comment by greg-db** [comment]
Yes, that's correct. You need to register the full exact redirect URI, including the path (in this case, the "/authorize" portion).
