### ISSUE TITLE
Handling the "incorrect_offset/.." error

### ISSUE THREAD

**Issue by IamSierraCharlie** [dropbox/dropbox-sdk-dotnet#118]
I'm performing a chunk upload of a file and emulating a failure of network by pulling the cable from my computer.  My code works fine to the point that it recovers and continues, but further down the line, a few chunks later, I get the error below.

```
The thread 0x2f34 has exited with code 0 (0x0).
Chunksize is now 8388608
IDX is now 1
Offset is now 8388608
session id is AAAAAAAAAZtYx1axktpPag
Exception thrown: 'Dropbox.Api.ApiException`1' in mscorlib.dll
Uplod failed with:
incorrect_offset/..
   at Dropbox.Api.DropboxRequestHandler.<Dropbox-Api-Stone-ITransport-SendUploadRequestAsync>d__13`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BoxUploader.Workers.<ChunkUpload>d__8.MoveNext() in C:\Users\steve\source\repos\BoxUploader\BoxUploader\Workers.cs:line 244

```

It happens more often when there is more than one simulated network failure.  My question - how can I handle this error ?  What I think I want to do if possible is find the correct offset, set it properly and then continue.

I'm looking at this:
https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_UploadSessionOffsetError.htm#!
but I don't understand how to use it.

**Comment by greg-db** [comment]
You can handle these `incorrect_offset` errors by catching the error and reading the correct offset from the response, via [`UploadSessionOffsetError.CorrectOffset`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_UploadSessionOffsetError_CorrectOffset.htm).

That would look something like:
```
try
{
    await client.Files.UploadSessionAppendV2Async(cursor, body: memStream);
}
catch (ApiException<UploadSessionLookupError> err)
{
    if (err.ErrorResponse.IsIncorrectOffset) {
        var correctOffset = err.ErrorResponse.AsIncorrectOffset.Value.CorrectOffset;  // get the correct offset from the server
        cursor = new UploadSessionCursor(sessionId, correctOffset);  // rebuild the cursor with the correct offset
        ...  // reset your file/stream to correct location
        ... // resume your upload session from that offset
    }
    else
    {
        ... // handle other errors here
    }
}
```

**Comment by IamSierraCharlie** [comment]
Thanks for your message @greg-db 
I've just one more question.
When I get the correct offset using:
`var correctOffset = err.ErrorResponse.AsIncorrectOffset.Value.CorrectOffset;`
The offset doesn't match the beginning of any offset that I would be expecting based around the chunk size that I created.  Is the right plan to start at the exact offset that the above command mentions or can I start at the beginning of the chunk based offset? 

so for example, if my chunk size is 8388608, each starting offset based on my for loop would be 
8388608, 16777216, 25165824 and so on.
If the corrected offset returns a number that is for example 23456782 (between the 2 offsets), should I start the upload at offset 16777216 or must I restart the upload at exactly what the corrected offset says?

Sounds silly, but this is an example of what I ran into today and I just wanted to check before I continued.
Many thanks for your help

**Comment by greg-db** [comment]
You'll need to resume at the exact `CorrectOffset` value supplied by the server. The Dropbox API won't accept further upload session chunks at any other offset. 

(If you're concerned that the incorrect data may have been sent and committed, you can always check the resulting [`FileMetadata.ContentHash`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_FileMetadata_ContentHash.htm).)
