### ISSUE TITLE
Support for proper usage of Task<T>.Result

### ISSUE THREAD

**Issue by JimiC** [dropbox/dropbox-sdk-dotnet#12]
Currently the SDK doesn't support proper implementation for usage of `Task<T>.Result` when called from nested `Task<T>` methods. In current version (2.3.3-beta) it results to a deadlock.
Consider the usage of `ConfigureAwait(false)` on every `await` that doesn't need the continued code to be executed on the main thread (mainly everywhere where `await` is used).

P.S: I'm using the SDK on a desktop app and I'm getting a deadlock when trying to use `Task<T>.Result`. I have tweaked the SDK in my app to implement `ConfigureAwait(false)` on every `RequestJsonStringWithRetry` and `RequestJsonString` in `DropboxRequestHandler` drilling down to and including `SendAsync(request, completionOption)`. After doing this everything works as expected.
Happy to provide a PR if wanted.

Justification: https://youtu.be/H4EmfpsYcfs?t=3966

**Comment by qimingyuan** [comment]
Thanks for your feedback! We've added ConfigureAwait(false) to SendAsync in v2.3.4.

**Comment by JimiC** [comment]
Updated to 2.3.4. Still not working properly. `ConfigureAwait(false)` needs to added to the entire chain  (i.e. `RequestJsonStringWithRetry ` and `RequestJsonString `).

**Comment by qimingyuan** [comment]
This should be fixed in 2.3.5.

**Comment by JimiC** [comment]
Updated to 2.3.5. Yeap, it's works properly now. Thanks a lot.
