### ISSUE TITLE
How to get more information of files?

### ISSUE THREAD

**Issue by Englbach** [dropbox/dropbox-sdk-dotnet#14]
var list = await dbx.Files.ListFolderAsync(string.Empty);
                foreach(var item in list.Entries.Where(i=>i.IsFile))
                {
                    item.Name;
                }

I want to get all folder and file to listbox(name of files, size of file....)

**Comment by greg-db** [comment]
It looks like you already have the basic idea around how to list files and folders. You have code for getting file names, and to get the size, just use [the `Size` property](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_FileMetadata_Size.htm).

Also, don't forget to use [`ListFolderContinueAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesRoutes_ListFolderContinueAsync_1.htm) to keep getting the rest of the entries if [`ListFolderResult.HasMore`](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_Files_ListFolderResult.htm) is true.

Using [`ListBox`](https://msdn.microsoft.com/en-us/library/system.windows.forms.listbox(v=vs.110).aspx) is outside the scope of the Dropbox .NET SDK project and support though, so I recommend looking at the documentation for that.
