### ISSUE TITLE
Where is  UsersStore.mdf?

### ISSUE THREAD

**Issue by RonaldPaguay** [dropbox/dropbox-sdk-dotnet#15]
SimpleBlogDemo/web.config makes a reference to this database, but couldn't find it and I'm unable to run the demo. Sorry if newbie question.

**Comment by greg-db** [comment]
That should get created automatically, in the App_Data folder, when you run the project.

When you say you can't run it, what does happen? What error(s) are you getting?

**Comment by RonaldPaguay** [comment]
Was getting "A network-related or instance-specific error occurred while establishing a connection to SQL Server...".

Reason was localdb v12 changes Data Source part of connectionString for "MSSQLLocalDB".
connectionString="Data Source=MSSQLLocalDB; ..."
