### ISSUE TITLE
Strong-Naming the Library

### ISSUE THREAD

**Issue by fahadabdulaziz** [dropbox/dropbox-sdk-dotnet#173]
**Why is this feature valuable to you? Does it solve a problem you're having?**
Strong-Naming the library is required to be referenced on strong-named project. we cannot use this library unless it signed.
Also per .NET guidelines for it suggested as best practice to sign the library. [.NET Library Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/get-started)

**Describe the solution you'd like**
Just library signing :-)

**Describe alternatives you've considered**
(StrongNamer) but we try to get rid of it and any library that is not signed.

**Additional context**
Big Thanks :-)

**Comment by greg-db** [comment]
Thanks for writing this up! I can't make any promises, but I'll ask the team to implement this.

**Comment by smoeller-liveid** [comment]
Same for us. We cannot use if not strong name signed. So please consider strong name signing. Thanks.

**Comment by greg-db** [comment]
@smoeller-liveid Thanks for the note!

**Comment by connorworley** [comment]
Hi, the newly released v6.0.0 should be strong-named and available via NuGet. Please let me know if you encounter any issues with it.
