### ISSUE TITLE
Dropbox access from a .Net service ?

### ISSUE THREAD

**Issue by RegisStGelais** [dropbox/dropbox-sdk-dotnet#186]
Hello all,

I need to build a .Net service that will pull files from a Dropbox account, parse it and then push the data to an SQL server.

I know from experience that on Android and iOS we need to have a UI to allow the user to enter its credentials and also accept the access requests.

Is there a way for my .Net service to login to the Dropbox account without any user interactions using the credentials stored in a secured file ?

 Thanks

**Comment by greg-db** [comment]
No, your app needs to send the user through the OAuth app authorization flow to have them authorize the app to receive an access token and refresh token. Your app should not directly handle Dropbox user credentials (email and password). Note that once you process the authorization flow, you can store and re-use the tokens, without further manual user intervention. Please refer to [the OAuth Guide](https://www.dropbox.com/lp/developers/reference/oauth-guide) for more information. The .NET SDK also includes [an OAuth helper](https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_DropboxOAuth2Helper.htm).

**Comment by RegisStGelais** [comment]
Tokens expirers after some time is I'm not mistaken.

OneDrive have other authorization flow process that allows for client authentification rather than user authentification.

**Comment by greg-db** [comment]
New Dropbox API access tokens are short-lived and expire after several hours by default, but you can use them in conjunction with refresh tokens to maintain long-term access without further manual user interaction. Please refer to [the OAuth Guide](https://www.dropbox.com/lp/developers/reference/oauth-guide) and [authorization documentation](https://www.dropbox.com/developers/documentation/http/documentation#authorization) for information on using that functionality.

**Comment by RegisStGelais** [comment]
Ok,  thanks for the info.

I will look it up.
