### ISSUE TITLE
Cannot get root folder using the SDK - doesn't match Regex

### ISSUE THREAD

**Issue by mohammadbadiul** [dropbox/dropbox-sdk-dotnet#192]
**Describe the bug**
When trying to get root folder using the dropbox API, if I enter "/" as input, I receive error `Specify the root folder as an empty string rather than as "/".` and if I enter empty string("") as input I receive error `Value should match pattern '\A(?:(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?))\z' (Parameter 'path')`. I tested the `ListFolderAsync` and `GetMetadataAsync` methods and the issue occurred in both. I suspect this will happen in other methods as well.

**To Reproduce**
Here's my code -
```
           var response = await _client
                .AsMember(memberId)
                .Files.GetMetadataAsync("").ConfigureAwait(false);
```

**Expected Behavior**
The SDK methods should either accept "" or "/" as root folder.

**Actual Behavior**
Cannot specify root folder using "" or "/".

**Screenshots**

**Versions**
* What version of the SDK are you using? 5.5.0
* What version of the language are you using? .netstandard 2.1(C# 8.0)
* What platform are you using? (if applicable) 

**Additional context**

**Comment by greg-db** [comment]
When referring to the root folder, you should use the empty string `""` as the `path`.

Note that the `GetMetadataAsync` method does not support the root folder though.

If you want to list the contents of the root folder, you should start with [`ListFolderAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm) with a `path` of the empty string `""`, which does support that.
