### ISSUE TITLE
Can't authenticate client when using no redirect URL

### ISSUE THREAD

**Issue by ThatOneBeagle** [dropbox/dropbox-sdk-dotnet#2]
Hi,

In the OAuth2 helper methods, the method "GetAuthorizeUri" can be called without a value for the "redirectUri" parameter. The next method that needs to be called, named "ProcessCodeFlowAsync" requires a redirectUri parameter (and is not optional).

Using a blank string/null as a parameter in this method still causes the redirectUri key to be sent in the request body, but with no value - which causes the API to complain that the redirectUri's do not match.

Thanks for the API, hopefully this was helpful.

**Comment by qimingyuan** [comment]
This is fixed: https://github.com/dropbox/dropbox-sdk-dotnet/commit/6907b4ab8b7934f94761ecbff26019cdb6be167a

Thanks for reporting!
