### ISSUE TITLE
DropboxClien.Files.ListFolderAsync and pagination

### ISSUE THREAD

**Issue by prakashguru** [dropbox/dropbox-sdk-dotnet#20]
Hi, 

Is there a way to limit the no of records returned from the ListFolderAsync() method? 

The list_folder api supports pagination and returns cursor. But I am unable to find the maximum limit for this api. When tested it returns more than 1000 files. Is there a way to limit it as like the search api max_results? 

https://www.dropbox.com/developers/documentation/http/documentation#files-search

Thanks,
Prakash

**Comment by greg-db** [comment]
No, there currently isn't a way to limit the number of entries returned by this method. We'll consider this a feature request though.

**Comment by greg-db** [comment]
You can now set an approximate limit on the `listFolder` page size using the `limit` parameter:

https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm
