### ISSUE TITLE
Access token problem

### ISSUE THREAD

**Issue by ohanaresch** [dropbox/dropbox-sdk-dotnet#21]
Hello.

I'm trying to use the SimpleBusinessDashboard example. I've created the app, and I set the App key and the App secret at config. Although I'm getting the error: _"Error in call to API function "team/get_info": This is a DfB team management function.  The OAuth 2 access token you provided is for a specific Dropbox user account and does not work with this function."_

I only need an app example for uploading and viewing using V2.

Am I missing something? Tks.

**Comment by greg-db** [comment]
This error indicates that your app key, app secret, and access token are for a "Dropbox API" app, which is linked to individual users, as opposed to a "Dropbox Business API app", which is linked to teams.

To use the Dropbox Business API functionality, you'll need to register a Dropbox Business API app, which you can do here:

https://www.dropbox.com/developers/apps/create

Alternatively, if you're not interested in Dropbox Business functionality, and instead just want to interact with single user accounts , e.g., to upload and download files, you should use one of the other example apps.
