### ISSUE TITLE
InitializeCertPinning breaks HTTPS for non-Dropbox URLs

### ISSUE THREAD

**Issue by RegisStGelais** [dropbox/dropbox-sdk-dotnet#211]
I'm having the same issue as in issue #74 
My app implements both Dropbox and MsGraph (OneDrive)
Where do I find the public key byte array that DropboxCertHelper.IsKnownRootCertPublicKey requires as parameter ??

**Comment by greg-db** [comment]
@RegisStGelais I see you just closed this issue, so I presume you've already resolved it, but let us know if there's something we can help with.
