### ISSUE TITLE
Error in call 

### ISSUE THREAD

**Issue by ArslanAfzalBhatti** [dropbox/dropbox-sdk-dotnet#22]
Error in call to API function "team/get_info": This is a DfB team management function.  The OAuth 2 access token you provided is for a specific Dropbox user account and does not work with this function.
how can i get rid of this error ?

**Comment by greg-db** [comment]
This error indicates that you're using a "Dropbox API" app, which is linked to individual users, as opposed to a "Dropbox Business API app", which is linked to teams.

To use the Dropbox Business API functionality, you'll need to register a Dropbox Business API app, which you can do here:

https://www.dropbox.com/developers/apps/create

**Comment by ArslanAfzalBhatti** [comment]
ok but it says "You must be team administrator to complete this action"
when i click on "Generate Access Token' how will this resolve ?

**Comment by greg-db** [comment]
Only team admins can perform the authorization for Dropbox Business API apps. If you're not an admin of your team, you won't be able to generate an access token for it. Instead, you'd need to have an admin on your team go through the OAuth app authorization flow for your app.

**Comment by ArslanAfzalBhatti** [comment]
Well this is embarrassing but i can;t get from where i can set my team and
team admin ?

**Comment by greg-db** [comment]
If you're not an admin of your team, you won't be able to set an admin. You can find the list of your team admins here:

https://www.dropbox.com/account#work

**Comment by ArslanAfzalBhatti** [comment]
Thank you i got it :)
