### ISSUE TITLE
Microsoft.Net.Http.Client OR System.Net.Http

### ISSUE THREAD

**Issue by ikourfaln** [dropbox/dropbox-sdk-dotnet#23]
Hi,

Im working on project with ASP.NET Core running on .NET Core.
So Im asking if your project reference to Microsoft.Net.Http.Client to use HttpClient. If yes, you need to remove this reference, this is obsolete now that CoreCLR has a functioning HttpClient. Microsoft.Net.Http should be used with traditional ASP.NET applications (MVC 5 for example) and does not work with .NET Core. So let ASP.NET Core developers be happy.

Thank you for your hard work

**Comment by qimingyuan** [comment]
Thanks for your comments! This projects references System.Net.Http and should work fine wig .Net core.

**Comment by ikourfaln** [comment]
Okkkkkkkkk @qimingyuan 
Thanx for replay
