### ISSUE TITLE
DropboxClient in Winforms C# - changing default timeout

### ISSUE THREAD

**Issue by davsun55** [dropbox/dropbox-sdk-dotnet#243]
The default timeout when creating a new DropboxClient is 100 secs.

In my application, I don't need it to be more than 10-15 secs. If Dropbox is unavailable the app can continue until the next app execution.

How can I change the timeout? I can't see how to in any of the documentation.

I'm using close to the latest version: Runtime v4.0.30319, Version 6.6.0.0.

Thanks,

David

**Comment by greg-db** [comment]
You can find an example of setting custom timeouts here:

https://github.com/dropbox/dropbox-sdk-dotnet/blob/b5dff871d353c46dcdf61f0319a10be4ed0b8c0c/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L70

Hope this helps!

**Comment by davsun55** [comment]
> You can find an example of setting custom timeouts here:
> 
> https://github.com/dropbox/dropbox-sdk-dotnet/blob/b5dff871d353c46dcdf61f0319a10be4ed0b8c0c/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L70
> 
> Hope this helps!

Hi Greg,

Pardon the question, but this is all I have done in my working Dropbox implementation:

Setup: DropboxClient dbc = new DropboxClient("XXX My key XXX");
Then the functions - eg:  var lfrLlist = DBClient.Files.ListFolderAsync("FileFoldder", false, false, false);

I have not done any of the additional functions in the demo link above like:
DropboxCertHelper.InitializeCertPinning();
var httpClient = new HttpClient(new WebRequestHandler { ReadWriteTimeout = 10 * 1000 })
http.GetContextAsync();
GetAccessToken()

Do I have to go the whole route in the demo, to change the timeout with the technique I'm using?

Thanks and appreciated.

David

**Comment by greg-db** [comment]
No, you don't need to perform all of those operations. You only need to perform the parts directly related to the timeouts. That is, set up the `WebRequestHandler` and `HttpClient` with the timeouts, and use that `HttpClient` to make a `DropboxClientConfig` and then a `DropboxClient` with that `DropboxClientConfig.`

The other operations are unrelated. (For example, `InitializeCertPinning` is an additional optional security feature, and `GetContextAsync` and `GetAccessToken` are related to implementing the OAuth app authorization flow.)

**Comment by davsun55** [comment]
Thank you. Works perfectly!  😊
