### ISSUE TITLE
Unity3D compatability

### ISSUE THREAD

**Issue by WebVRRollerCoaster** [dropbox/dropbox-sdk-dotnet#25]
Is this SDK compatible with Unity3D?
Please let me know, thank you.

**Comment by greg-db** [comment]
I don't believe so, but we'll consider it a feature request.

**Comment by cakoose** [comment]
Different versions of Unity3D support different subsets of the .Net API ([compatibility chart](http://docs.unity3d.com/412/Documentation/ScriptReference/MonoCompatibility.html)).

We don't officially support Unity3D, so we haven't tried it ourselves.  But there's a chance it works as-is, so you might want to try it out and see.

**Comment by connorworley** [comment]
Closing the loop here- we target .NET Standard 2.0, which [Unity >= 2018.1 supports](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support).
