### ISSUE TITLE
Did not find any where to get the mimetypes of a file!

### ISSUE THREAD

**Issue by chandan-g-bhagat** [dropbox/dropbox-sdk-dotnet#29]

**Comment by cakoose** [comment]
Dropbox doesn't store MIME type information.  You can try making your own MIME type guess based on the file extension or file contents.

I found a few options for guessing based on the file extension (NOTE: I haven't tried any of them):
- [System.Web.MimeMapping](https://msdn.microsoft.com/en-us/library/system.web.mimemapping.getmimemapping(v=vs.110).aspx)
- https://github.com/samuelneff/MimeTypeMap

**Comment by greg-db** [comment]
That's correct, the API/SDK don't currently offer MIME types, and I don't believe there are plans to do so. We'll consider this a feature request though.

**Comment by speedchandu** [comment]
@cakoose Thank you for the suggestion!
@greg-db Well I guess, that feature would be better.
One more thing, i would like to ask
How do i get the list of shared files not the folder? Shared folder is already showing up.

**Comment by greg-db** [comment]
@speedchandu It sounds like you're looking for the [`ListReceivedFilesAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingRoutes_ListReceivedFilesAsync_1.htm) and [`ListReceivedFilesContinueAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingRoutes_ListReceivedFilesContinueAsync_1.htm) methods.

**Comment by maxbeaudoin** [comment]
It's possible to obtain a file's MIME type like this :

1. Obtain a temporary link (https://api.dropboxapi.com/2/files/get_temporary_link);
2. Execute a HEAD request on the temporary link (https://*.dl.dropboxusercontent.com/*/file);
3. Read the response Content-Type header.

**Comment by chandan-g-bhagat** [comment]
well, its been a long time. I believe it was sorted out 5 years back. Thanks guys! :)
