### ISSUE TITLE
Throw out the whole SDK

### ISSUE THREAD

**Issue by gsmith91** [dropbox/dropbox-sdk-dotnet#294]
This is structured like you asked a drunken room full of monkeys to build something...

How can something so simple have such a mess of an interface? It should take no more than three lines of code to do a basic upload and yet you have just an absolute mess here.

I almost sent this earlier but decided to give it another shot... but NOPE, I was right. This is trash.

It would honestly have been less work to host my own file server and write this functionality from scratch at this point. Oh boy is "engineering" in trouble.

**Comment by greg-db** [comment]
Thanks for the feedback! There aren't currently plans to rewrite this whole SDK so I'll close this out, but I've sent this feedback along to the team internally.
