### ISSUE TITLE
Search by file content not working

### ISSUE THREAD

**Issue by ipvalverde** [dropbox/dropbox-sdk-dotnet#3]
I'm trying to execute a search in my dropbox folder searching inside file content but I'm not having success in doing so.
I'm trying to execute the following code, looking for the term *Start*:

`return await this.client.Files.SearchAsync(new SearchArg("", "Start", mode: SearchMode.FilenameAndContent.Instance));`

In my tests, I have four files that I'm expecting as the result of this search:
1. A pdf file with the term *Start* in its content only;
2. A docx file with the term *Start* in its content only;
3. A pdf file with the term *Start* in its name and content;
4. A zip file with the term *Start* in its name;

The result of this search only brings me the third and forth files, ignoring the search mode specified, since I'm using *SearchMode.FilenameAndContent.Instance*.

I don't know if there is an issue with dropbox server right now or if the file content search is no longer supported. If it is not supported anymore, I think it would be a good idea to flag it as obsolete.

**Note:** Every file was last modified in more than 24 hours, so I don't think it is related with indexing.

**Comment by smarx** [comment]
Is the account you're testing with a Dropbox Business account? Full-text search only works for Dropbox Business accounts (on the website and in the API).

(And yes, we'll be updating the documentation to explain this.)

**Comment by ipvalverde** [comment]
Thats it! I'm using a *regular* Dropbox account.
Thank you for letting me!

Well, it's not directly linked to this dropbox sdk, but would be nice to have it documented in the rest documentation also.
https://www.dropbox.com/developers/documentation/http#documentation-files-search
