### ISSUE TITLE
ListFolderLongpollAsync always throw TaskCanceledException

### ISSUE THREAD

**Issue by Ready4Next** [dropbox/dropbox-sdk-dotnet#30]
hi,

It works using your website test tool, so it isn't the API itself.

Here is the code:
```
// Create the token source.
                if (!CancelTokens.ContainsKey(path))
                {
                    var wtoken = new CancellationTokenSource();
                    // Add this token
                    CancelTokens.AddOrUpdate(path, wtoken, (s, source) => wtoken);

                    // First search 
                    var delta = dbx.Files.ListFolderAsync(path, Recursive).Result;

                    // Set the task.
                    var task = NeverEndingTask.CreateNeverEndingTask(now =>
                    {
                        bool changes = false;
                        while (!changes)
                        {
                            ListFolderLongpollResult result = null;

                            // Always Throw TaskCanceledException
                            result =
                                dbx.Files.ListFolderLongpollAsync(delta.Cursor, 120).Result;

                            if (result.IsNotNull())
                            {
                                changes = result.Changes;
                                if (result?.Backoff.HasValue ?? false)
                                {
                                    Thread.Sleep(result.Backoff.Value.ToType<int>()*1000);
                                }
                            }

                            // Wait
                            Thread.Sleep(pollDelay);
                        }

                        // Ask to continue
                        delta = dbx.Files.ListFolderContinueAsync(delta.Cursor).Result;
                        OnChanges?.Invoke(delta);
                    }, wtoken.Token);

                    // Start the task.  Post the time.
                    task.Post(DateTimeOffset.Now);
```

And the exception:

> [TaskCanceledException: Une tâche a été annulée.]
> 
> [AggregateException: Une ou plusieurs erreurs se sont produites.]
>    System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +4465776
>    IMSUtils.DropBox.DropBoxListener.StartWatchPath(String path, Action`1 OnChanges, Int32 pollDelay, Boolean Recursive) in D:\Devel\Icor Projects\IMSUtils\DropBox\DropBoxListener.cs:154
>    IMSUtils.DropBox.DropBoxListener.StartWatchCustomerInfos() in D:\Devel\Icor Projects\IMSUtils\DropBox\DropBoxListener.cs:245
>    IcorDatabase.BusinessObjects.ProfileRepository`1.LogUserProfile(Int32 UserId) in D:\Devel\Icor Projects\IcorDatabase\BusinessObjects\ProfileRepository.cs:593
>    IMSMain.WebsiteUser.<LogUser>d__62.MoveNext() in D:\Devel\Icor Projects\IMSMain\IMSMain\WebsiteUser\ICOR_Profile.cs:468
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
>    System.Runtime.CompilerServices.TaskAwaiter.GetResult() +28
>    IMSWebAppSync.Controllers.<Index>d__0.MoveNext() in D:\Devel\Icor Projects\IMSWebAppSync\IMSWebAppSync\Controllers\HomeController.cs:99
>    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +13891908
>    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +61
>    System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +93
>    System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +22
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +386
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +186
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +44
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +67
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +399
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +137
> 

Thanks in advance,

**Comment by Ready4Next** [comment]
There is also another exception:

> On ThrowForNonSuccess with System.Runtime.CompilerServices.TaskAwaiter 
> StackTrace:
> à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> à Dropbox.Api.DropboxRequestHandler.d__20.MoveNext() 
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée --- 
> à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> à Dropbox.Api.DropboxRequestHandler.d__10.MoveNext() 
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée --- 
> à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> à Dropbox.Api.DropboxRequestHandler.d__0`3.MoveNext() 
> --- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée --- 
> à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) 
> à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
> à System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
> à IMSUtils.DropBox.DropBoxListener.<>c__DisplayClass10_0.<b__0>d.MoveNext()
>

**Comment by Ready4Next** [comment]
Using a custom wrapper directly to the API works nicely.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by Ready4Next** [comment]
You're welcome :)

If I can do anything else, please let me know.

**Comment by qimingyuan** [comment]
TaskCanceledException hides the actual exception which I think is http response timeout. Default timeout for http client is 100 seconds which is smaller than the value in the your code (120 seconds) and that's why a timeout exception is thrown. To use longpoll, you need to make sure the timeout configured [`here`](<https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/Examples/SimpleTest/Program.cs#L49) is larger than the value of timeout parameter.
