### ISSUE TITLE
Documentation is missing from gh pages.

### ISSUE THREAD

**Issue by AutumnThyme** [dropbox/dropbox-sdk-dotnet#305]
**Before you start**
Have you checked StackOverflow, previous issues, and Dropbox Developer Forums for help?
Not really applicable.

**What is your question?**
A clear and concise description of the question.
On the gh pages, there is a link to: 
https://dropbox.github.io/dropbox-sdk-dotnet/html/R_Project_DotNetApiDocumentation.htm
for the API documentation however it returns a 404.

**Comment by greg-db** [comment]
Thanks for the note! We've recently updated the docs so the link changed, and we've already updated [the link](https://dropbox.github.io/dropbox-sdk-dotnet/) in the readme, so that will be updated in the next build of the docs on GitHub Pages.
