### ISSUE TITLE
Processor architecture mismatch when building for x64 (UWP)

### ISSUE THREAD

**Issue by tipa** [dropbox/dropbox-sdk-dotnet#306]
**Describe the bug**
With the latest v6.29.0, the library cannot be used in x64 UWP projects any more. No problems with v6.28.0

**To Reproduce**
Add the v6.29.0 NuGet to a blank UWP app, try to run the app with the x64 architecture mode selected.

**Expected Behavior**
App can be built

**Actual Behavior**
App cannot be built. Error:

`There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "C:\Users\timop\.nuget\packages\dropbox.api\6.29.0\lib\netstandard2.0\Dropbox.Api.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	
`

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by greg-db** [comment]
This should be fixed with v6.30.0. Please try that and let us know if you're still seeing any issues. Thanks!

**Comment by tipa** [comment]
Works again, thanks a lot for the quick fix!
