### ISSUE TITLE
Support for Dropbox-API-Select-User header?

### ISSUE THREAD

**Issue by mmedic** [dropbox/dropbox-sdk-dotnet#319]
When using Business account and Team features, it is necessary to set Dropbox-API-Select-User? I am not seeing the ability to set this in the SDK.

**Comment by greg-db** [comment]
This is available in this SDK via [the `AsMember` method](https://dropbox.github.io/dropbox-sdk-dotnet/gh-pages/obj/api/Dropbox.Api.DropboxTeamClient.html#Dropbox_Api_DropboxTeamClient_AsMember_System_String_).
