### ISSUE TITLE
get access token from oauth1token and oauth1tokensecret 

### ISSUE THREAD

**Issue by MansoorJafari9** [dropbox/dropbox-sdk-dotnet#326]
Hello

I have 2 question.

1-

I want to login in my site with your api and I don't want login in with web page.

I have appkey and appsecrect and I want to get access token with this URL "https://api.dropboxapi.com/2/auth/token/from_oauth1"

but every time I try to get access token. after that I have an error

{ "error": { ".tag": "invalid_oauth1_token_info" }, "error_summary": "invalid_oauth1_token_info/..." }

 

for this parameters below

{ "oauth1_token": "....", "oauth1_token_secret": "..." }

How can get it?

 

2-

I have a service that I want to upload multiple file ( about 10000 file and each file about 100 KB) everyday and maybe I want to download and edit multiple files.

I want to know Does your service support this huge requests or maybe you ban my ip?

**Comment by greg-db** [comment]
I see you also posted this on the forum, so I'll close this issue in favor of [that thread](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/get-access-token-from-oauth1token-and-oauth1tokensecret/td-p/623612).
