### ISSUE TITLE
It's a bandwith limit to download with sdk?

### ISSUE THREAD

**Issue by ghiboz** [dropbox/dropbox-sdk-dotnet#36]
hi all!
i've a free account and I use the sdk to download some files from the dropbox account to multiple pc..
it's a limitation or not?

thanks in advance

**Comment by greg-db** [comment]
If you're referring to the [`DownloadAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/Overload_Dropbox_Api_Files_Routes_FilesRoutes_DownloadAsync.htm) method, no, there isn't a bandwidth limit. (The API in general does have a rate limiting system, but that only operates on the number of calls over time, and not bandwidth.)

**Comment by ghiboz** [comment]
thanks @greg-db !
and how much is the number of calls over time??

**Comment by greg-db** [comment]
We don't have any specific numbers documented, but is only designed to prevent abuse, and is accordingly relatively generous. Further, the limits operate on a per-user basis. That being the case, you generally don't need to worry about hitting it in normal use.
