### ISSUE TITLE
get shared link

### ISSUE THREAD

**Issue by kanuvic** [dropbox/dropbox-sdk-dotnet#37]
Hello,

I use CreateSharedLinkWithSettingsAsync  to create a shared link for a file.
However, I will get shared link already exists error.
How can I obtain the shared link if the file has already been shared? I cannot find any url field from the file metadata, and GetSharedLinkFileAsync is not for this purpose.

Thanks

**Comment by greg-db** [comment]
You can use [`ListSharedLinksAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingUserRoutes_ListSharedLinksAsync_1.htm) with the `path` of the file, and `directOnly=true` to get the existing link for the file.
