### ISSUE TITLE
Business endpoints are not supported

### ISSUE THREAD

**Issue by saguiitay** [dropbox/dropbox-sdk-dotnet#4]
The various Business API endpoints are not yet supported by this SDK, which makes it very limited.

**Comment by qimingyuan** [comment]
Thanks for your feedback! The Business API endpoints should be available in the next few weeks.

**Comment by saguiitay** [comment]
Is there an ETA on this?

**Comment by qimingyuan** [comment]
The initial batch of business endpoints are released in v2.3.0.
