### ISSUE TITLE
Problem with downloadAsync

### ISSUE THREAD

**Issue by krzychu2** [dropbox/dropbox-sdk-dotnet#40]
When calling DownloadAsync shows me this error

"Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'. "Message = "One or more errors occurred. (Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'. 

My code

 public async Task<byte[]> Download(string folder, string file)
        {

            using (var response = await Client.Files.DownloadAsync("/" + folder + "/" + file))
            {
                return await response.GetContentAsByteArrayAsync();
            }
        }

**Comment by qimingyuan** [comment]
What's your .NET version? Is it possible to upgrade to 4.5 or above? If you are using .NET 4.0 an is not able to upgrade. Could you try patching this (https://support.microsoft.com/en-us/kb/2468871) so that PCL libraries can be properly loaded?

**Comment by krzychu2** [comment]
I'm sorry I forgot to give .NET version

I use .netstandard Dotnet Core 1.6 and 1.1

**Comment by qimingyuan** [comment]
The SDK contains PCL with profile111 which is [compatible](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) with .net standard 1.1 and above. I tested it on dotnet core 1.0/1.1 with .net standard 1.1/1.6 but I am not able to repro your issue. Would you mind providing a sample project where I can reproduce the issue?

**Comment by vors** [comment]
I was trying to build the SDK with dotnet core.

I have impression that even if you manage to run the code, there is a [problem with ContentType in dotnet core](https://github.com/PowerShell/PowerShell/issues/3131#issuecomment-285552484) that can prevent using the SDK.

**Comment by vors** [comment]
Corefx issue: https://github.com/dotnet/corefx/issues/16947

**Comment by qimingyuan** [comment]
Close this one as native support for .NET Core has been added in v4.9.0
