### ISSUE TITLE
Blog demo

### ISSUE THREAD

**Issue by sanjayssk** [dropbox/dropbox-sdk-dotnet#42]
I'm now successfully able to run the Blog example. But I don't see any link or menu to create articles. Am I missing something? I'm using it on VS 2015 and had to do quite a bit of jugglery with Nuget packages to finally make it work. Thanks.

**Comment by greg-db** [comment]
The blog demo is working for me. I'm able to register, connect my Dropbox account, and add and edit articles using the interface in the browser.

Can you elaborate on what's not working, or share some screenshots showing what you're seeing? Thanks in advance!

**Comment by rogebrd** [comment]
Closing due to lack of response by reporter.
