### ISSUE TITLE
LongPoll timeout not correctly preparing HttpClient

### ISSUE THREAD

**Issue by shaakir** [dropbox/dropbox-sdk-dotnet#44]
If I wanted a longer timeout, say 5 minutes (assuming DropBox supports it), the HttpClient used times out.

Doc says "plus up to 90 seconds". So if we go 30s (the default) + 90s = 120s, or 2 minutes.

Default timeout for HttpClient is 100s (1min 40s). (https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout%28v=vs.110%29.aspx)

I think the timeout should be set based on the supplied timeout (of, for example ListFolderLongPollArg.Timeout).

I don't see it used / passed anywhere (besides as part of the call content).

Please correct my misunderstanding if I am wrong.

**Comment by shaakir** [comment]
I suppose the following code will fix it. It would be nice if the methods checked for the condition where a call may exceed the current timeout and either die or warn (the programmer) - or a comment in the method description to refer the programmer to DropboxClientConfig?
```
DropboxClientConfig dcc = new DropboxClientConfig();
dcc.HttpClient = new HttpClient();
dcc.HttpClient.Timeout = new TimeSpan(0,0,5,0);
using (var dbx = new DropboxClient(Properties.Settings.Default.DropboxApiClientKey))
```

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by qimingyuan** [comment]
We've increase default timeout for long poll requests to be 480 seconds. Let me know if you still seeing issues.
