### ISSUE TITLE
DropboxOAuth2Helper uses v1 URIs

### ISSUE THREAD

**Issue by rboyts** [dropbox/dropbox-sdk-dotnet#48]
Currently we can see that you are still using v1 URIs in you Dropbox.Api library. 
We are using Dropbox.Api version = 0.1.6274.34602. 

Issues found in following places:
DropboxOAuth2Helper class, Method GetAuthorizeUri, line 254:
`var uriBuilder = new UriBuilder("https://www.dropbox.com/1/oauth2/authorize")`

DropboxOAuth2Helper class, Method ProcessCodeFlowAsync, line 375:
`var response = await httpClient.PostAsync("https://api.dropbox.com/1/oauth2/token", content);`

Could you please clarify why are you still using v1 URIs? 
And when do you plan to fix this?

**Comment by qimingyuan** [comment]
Thanks for pointing this out. The one without /1/ should be used in all cases. We will update the URL in DropboxOAuth2Helper in our next release.

**Comment by rboyts** [comment]
Could you please provide us with ticket id or details regarding when this issue is going to be fixed?

**Comment by greg-db** [comment]
We'll follow up here and close this issue when this is resolved. In the meantime, you can continue using the SDK as is. The functionality is the same.
