### ISSUE TITLE
Membership information of a folder is not available

### ISSUE THREAD

**Issue by saguiitay** [dropbox/dropbox-sdk-dotnet#5]
In v1 of the API, the `/metadata` endpoint allowed the retrieval of membership information of a folder (via the `include_membership` option). This allowed the ability to see who a specific folder was shared with.

Now, in v2, that information is not available.

**Comment by qimingyuan** [comment]
This is on our roadmap and should be supported soon.

**Comment by qimingyuan** [comment]
shared_folder_id field has been added for folder metadata and shared folder endpoints can be called to get membership info.
