### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Nicholson85** [dropbox/dropbox-sdk-dotnet#50]
Is there an elegant way to implement server side pagination using this API?

I see there are 2 methods, ListFolderAsync & SearchAsync;

**ListFolderAsync** does not seem to allow me to set a limit on the number of records returned or identify what the paging limit is.  Although **ListFolderResult** contains the property "HasMore", implying that pagination is supported.  Further evidenced by the '**ListFolderContinueAsync**' method which expects a cursor returned by **ListFolderResult**

**SearchAsync** allows you to set a paging limit and **SearchResult** contains the property, "More", but does not allow you to supply an empty string or a wildcard as the search term to return all records.

Is there something I am missing here?

**Comment by greg-db** [comment]
For [`ListFolder`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm), you can't set a certain page size, nor is any particular page size guaranteed. You should just have your app call back to [`ListFolderContinue`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderContinueAsync_1.htm) with the latest [`ListFolderResult.cursor`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_ListFolderResult_Cursor.htm) if [`ListFolderResult.HasMore`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_ListFolderResult_HasMore.htm) is true, and repeat until it is false.

The [`Search`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_SearchAsync.htm) functionality doesn't offer a wildcard feature. If you need to retrieve all entries in the account or in a particular subfolder, you should use [`ListFolder`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm). When using [`Search`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_SearchAsync.htm) though, if [`SearchResult.More`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_SearchResult_More.htm) is true, you can call back to [`Search`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_SearchAsync.htm) again, and supply the [`SearchResult.Start`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_SearchResult_Start.htm) value as the `start` parameter for the [`Search`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_SearchAsync.htm) call.

**Comment by greg-db** [comment]
You can now set an approximate limit on the [`ListFolder`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm) page size using the `limit` parameter.
