### ISSUE TITLE
team_log/get_events is not covered

### ISSUE THREAD

**Issue by vors** [dropbox/dropbox-sdk-dotnet#51]
It would be awesome to get https://www.dropbox.com/developers/documentation/http/teams#team_log-get_events counterpart for the SDK.

**Comment by greg-db** [comment]
That endpoint was added recently, so it should be available in the next release of the SDK.

**Comment by greg-db** [comment]
The documentation for this can be found here:

https://dropbox.github.io/dropbox-sdk-dotnet/html/T_Dropbox_Api_TeamLog_Routes_TeamLogTeamRoutes.htm
