### ISSUE TITLE
Unable to run blog demo due to DB connection

### ISSUE THREAD

**Issue by AlfonsoML** [dropbox/dropbox-sdk-dotnet#52]
I'm sorry as this is not a problem about the API itself, but I'm trying to run the demo in order to understand the workflow but I'm unable to run it.

I'm using Visual Studio 2017 Community Edition with SQL Server Express 2014.  
By opening the project I get a warning that I don't have SQL 2012 installed and that the DB will be upgraded by double clicking, but as there's no .mdf, I can't click anything.

I've tried to edit the connection string in web.config to 
`	  <add name="UsersStore" connectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\UsersStore.mdf;Integrated Security=True" providerName="System.Data.SqlClient" />`
I've recreated the App_Data folder and set permission to control it to Everyone.  
But when I run the project it stops at global.asax Application_Start `if (store.Users.Count() == 0)`
with an exception System.Data.SqlClient.SqlException, System Error 5 (Access denied) and

An attempt to attach an auto-named database for file C:\Inetpub\ ... \App_Data\UsersStore.mdf failed. A database with the same name exists, or specified file cannot be opened, or it is located on UNC share.

I've tried to search for an answer but I'm unable to find the solution because what I've found so far applies for existing .mdf files, not about creating automatically one so I don't know what's exactly the part that it's failing.

**Comment by qimingyuan** [comment]
This demo project uses localdb which comes with VS2017. You just need to change `v11.0` in the old connection string to be `MSSQLLocalDB` i.e.
```
<add name="UsersStore" connectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\UsersStore.mdf;Integrated Security=True" providerName="System.Data.SqlClient" />
```

**Comment by AlfonsoML** [comment]
Thank you. It worked perfectly!

I've created a pull request #53 to put this info in the web.config and help other clueless people like me.
