### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by ErwanJes** [dropbox/dropbox-sdk-dotnet#54]
Where can I find the license for Dropbox .Net SDK?

Is it the same as the iOS one ?
https://github.com/dropbox/SwiftyDropbox/blob/master/LICENSE

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-support/New-license-for-dropbox-sdk-dotnet/m-p/224647#M12140 ]

You can find the license for the official Dropbox API v2 .NET SDK here:

https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/LICENSE
