### ISSUE TITLE
Missing files in the source code? e.g. Dropbox.Api\Dropbox.Api.csproj ?

### ISSUE THREAD

**Issue by horacioj** [dropbox/dropbox-sdk-dotnet#56]
Perhaps it is too late at night and I should be sleeping, but in the current v4.3.0 release I can't find anywhere Dropbox.Api\Dropbox.Api.csproj and many other files (Dropbox.Api.Portable.csproj, Dropbox.Api.Portable40.csproj, etc.)

Furthermore, dropbox-sdk-dotnet-4.2.6.zip is 2.21 MB and dropbox-sdk-dotnet-4.3.0.zip is just 1.32 MB
So, I guess some files are truly missing?
I don't see them in the current code either (https://github.com/dropbox/dropbox-sdk-dotnet)

**Comment by greg-db** [comment]
Hi @horacioj . These were intentionally removed in 1d9e231a50786f05dc4c1aba846e20994a99c4ce as they're automatically generated. You can follow [the instructions in the README](https://github.com/dropbox/dropbox-sdk-dotnet#building-from-source) to generate the source code if you'd like.

**Comment by horacioj** [comment]
So, the released 'source code' (https://github.com/dropbox/dropbox-sdk-dotnet/archive/v4.3.0.zip) is useless. `dropbox-sdk-dotnet-4.3.0.zip` is NOT the source code? It is something I have to compile with other tools (which I don't have nor need nor want to install) to get the source code? 

It doesn't make any sense. Some `cs` files are there, the `sln` file is there, but `csproj` files and more, need to be 'compiled' by phyton (and all its dependencies)? 


So, to actually get the source code, I need to generate it?, This would be:

- install `git` (I have but, but I shouldn't need it just for getting the release source code, right? The complete source code should be in the release (`dropbox-sdk-dotnet-4.3.0.zip`), otherwise, it is NOT the release.

- install `Python` (and make it functional in my machine). I don't need nor use nor want Python.

- install `Sandcastle` (and make it functional in my machine). Another tool I have to install and don't need nor want nor use.   

- Run `git submodule init`.  
Where? based on which repository? So, why do I have download the RELEASE `dropbox-sdk-dotnet-4.3.0.zip`? 
Do you mean, I have to `git clone dropbox-sdk-dotnet`? 
I don't want the current code or the git repository. I just need the release source code. which should be in the RELEASE .zip file. 

- Run other `git` and `python` stuff, and with luck I'll get the source code that should have been included in the release .zip file in the first place? 

I really don't get it. 

So, I'm stuck in `git submodule init`. Of course, it doesn't work with the unzipped `dropbox-sdk-dotnet-4.3.0.zip`. I need to clone the git repository? and then somehow checkout the v4.3.0 release? What  is the `dropbox-sdk-dotnet-4.3.0.zip` file for?

**Comment by horacioj** [comment]
In short: This was a mistake. Please fix it. 
**Regenerating the code should be optional, not mandatory**, same as  it is in many others SDKs including auto-generated code. 

If someone would like to play with python, sandcastle and whatever other tool you use, then fine. But this shouldn't be mandatory for anyone that simply need to get the source code. 

What's next? Include some PNGs with code it it, and some script to be run with tool XYZ that will do OCR in the PNGs and extract the source code? This would be exactly the same as you did here.

**Comment by greg-db** [comment]
Thanks for the feedback! The reason the SDK works like this is because it's generated from [dropbox-api-spec](https://github.com/dropbox/dropbox-api-spec), which describes the Dropbox API itself, so that a generator can be written for any platform.

Yes, `git submodule init` would be run inside the `dropbox-sdk-dotnet` repo, which you can get by `git clone`ing it.

In most cases, we recommend just installing from the NuGet package, so that you don't need to worry about any of the generation.

We certainly appreciate the feedback though. I just sent this along to the team, and they updated the v4.3.0 zip to include the generated files again. Hope this helps!

**Comment by horacioj** [comment]
Awesome, many thanks! I hope you'll keep doing the same for all future releases.

I wish I could simply use the NuGet package, but I have to tweak the code to integrate it into something else.
