### ISSUE TITLE
Check for file sync complete?

### ISSUE THREAD

**Issue by schmeed** [dropbox/dropbox-sdk-dotnet#58]
Is there a way via the API to just confirm if file has been synced between client and server?  That's the only thing I need to determine.

Thanks!

**Comment by greg-db** [comment]
Any filed listed by the API have been synced to the server. New files or new versions of new files may be in transit at any time though. The API doesn't offer a way to check if there are any new files or versions currently being uploaded. We'll consider it a feature request though.

**Comment by cakoose** [comment]
@schmeed: By "client", do you mean the API client app or do you mean the Dropbox Desktop client?
