### ISSUE TITLE
Problems with .NET standard 2.0 and Xamarin

### ISSUE THREAD

**Issue by modplug** [dropbox/dropbox-sdk-dotnet#61]
# Setup

Xamarin Forms latest pre-release.
I've added the latest Dropbox Api nuget package to my .NET standard 2.0 core project and to both my Android and iOS project. 

# Android
When I run the app on Android it fails with: 
```System.MissingMethodException: Method 'Dropbox.Api.Files.Routes.FilesUserRoutes.ListFolderAsync' not found.```

# iOS
When I run the app on iOS I get: System.MissingFieldException: Field ```'Dropbox.Api.DropboxRequestHandler/<Dropbox.Api.Stone.ITransport.SendRpcRequestAsync>d__5`3<TRequest_REF, TResponse_REF, TError_REF>.<>4__this' not found.```

Has anyone else experienced something like this? 
What's the deal with the Dropbox.Xamarin.API package?

**Comment by greg-db** [comment]
The Dropbox .NET SDK (on NuGet as [Dropbox.Api](https://www.nuget.org/packages/Dropbox.Api/)) isn't officially supported for Xamarin, so I'm afraid I can't offer help there. I'll send this along as a request for official Xamarin support though.

The [Xamarin.Dropbox.Api](https://www.nuget.org/packages/Xamarin.Dropbox.Api/) package may work better for you, but that's maintained by a third party, so we can't offer support for it.

There was also a thread about this earlier today though, with a solution that may help:

https://www.dropboxforum.com/t5/API-support/System-MissingFieldException-using-Dropbox-Api-4-3-1-on-Xamarin/m-p/241143#M13428

**Comment by hartez** [comment]
@modplug Out of curiosity, did the link Greg provided help? Also, with regard to the Android issue - what are your linker settings for the project? If you change Linking to "none", does the issue persist?

**Comment by modplug** [comment]
@hartez I fixed it by adding Microsoft.Bcl.Async to the iOS project. That is what the author of the Dropbox.Xamarin.API nuget did as well. As for Android, I got stuck and prioritized the iOS / core part of my app until the error has been resolved
