### ISSUE TITLE
shared links

### ISSUE THREAD

**Issue by RickySan65** [dropbox/dropbox-sdk-dotnet#63]
For some reason i can't get the shared links in a folder, it always returns null (or empty array)

here's the code i'm using

```
 DropboxClient client = GetDropboxClient(Profile);            
            string sharename = "";
            if (string.IsNullOrEmpty(Folder))
            {
                Folder = "/";
            }               
            try
            {
                ListSharedLinksResult results = await client.Sharing.ListSharedLinksAsync(Folder);
                sharename = string.Join(",", results.Links);
            }
            catch (Exception ex)
            {

            }

```
is it a known bug? or do i need to user another method?

**Comment by greg-db** [comment]
The [`ListSharedLinksAsync` method](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingUserRoutes_ListSharedLinksAsync_1.htm) will return links that "allow access to the given path - direct links to the given path and links to parent folders of the given path". 

You mentioned you're trying to get the shared links _in_ the folder though, which [`ListSharedLinksAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingUserRoutes_ListSharedLinksAsync_1.htm) won't return. You'll need to call it and specify the path(s) for the specific item(s) that you're looking for.
