### ISSUE TITLE
Need code example for path param in CreateSharedLinkWithSettingsAsync

### ISSUE THREAD

**Issue by mikemalter** [dropbox/dropbox-sdk-dotnet#64]
It would be helpful to have a code example in CreateSharedLinkWithSettingsAsync so I could know what value to pass in the path parameter.  In my case, an example would be "C:\Users\malter.JOYOUSLIVING\Dropbox\FoldernameLevel1\FolderNameLevel1\FileName.pdf".  Do I pass the entire path string or just everything right after Dropbox.  Not sure what to pass.  Also could use some guidance on the SharedLinkSettings param also.  We don't want the filelinks to be public, but only to those people who are authorized to access the folder.

Thank you.

**Comment by greg-db** [comment]
The path you supply should be the path in Dropbox, e.g., the [`Metatdata.pathLower`](https://dropbox.github.io/dropbox-sdk-dotnet/html/P_Dropbox_Api_Files_Metadata_PathLower.htm) as returned elsewhere in the API. For your sample, that would look like `"/foldernamelevel1/foldernamelevel1/filename.pdf"`.

Here's an example that uses the Dropbox .NET SDK to get a shared link for a file, either by creating a new one with settings, or retrieving an existing one:

    SharedLinkMetadata sharedLinkMetadata;
    SharedLinkSettings settings = new SharedLinkSettings(requestedVisibility:RequestedVisibility.Password.Instance, expires: DateTime.Now.AddMonths(1), linkPassword: password);
    try
    {
        sharedLinkMetadata = await this.client.Sharing.CreateSharedLinkWithSettingsAsync(path:path, settings:settings);
    }
    catch (ApiException<CreateSharedLinkWithSettingsError> err)
    {
        if (err.ErrorResponse.IsSharedLinkAlreadyExists)
        {
            var sharedLinksMetadata = await this.client.Sharing.ListSharedLinksAsync(path: path, cursor: null, directOnly: true);
            sharedLinkMetadata = sharedLinksMetadata.Links.First();
        }
        else
        {
            throw err;
        }
    }
    Console.WriteLine(sharedLinkMetadata.Url);

**Comment by mikemalter** [comment]
Greg,

This is very helpful.  Thank you.  I'll let you know how it goes.
