### ISSUE TITLE
Get size and url of a shared file?

### ISSUE THREAD

**Issue by cadilhac** [dropbox/dropbox-sdk-dotnet#68]
I am coming from fropnet, which is not v2 compatible. I am trying to convert some code but with no success so far. Here is a piece of code to get the size and url of a file shared by an app I registered in dropbox (to get api key and secret):

```
var _client = new DropNetClient(apikey, appsecret, accesstoken);
_client.UseSandbox = true;
var meta = _client.GetMetaData(dp, null, false, false);
var resp = _client.GetShare(dp, false);
// I can now redirect client to resp.Url
```

How to do the same thing with this lib please?
Thanks

**Comment by greg-db** [comment]
The equivalent of `GetMetadata` would be [`Files.GetMetadata`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_GetMetadataAsync_1.htm) if you just need the metadata for the particular item, or [`Files.ListFolder`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderAsync_1.htm) and [`File.ListFolderContinue`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderContinueAsync_1.htm) if you need the list of files in a folder.

The equivalent of `GetShare` would be [`Sharing.CreateSharedLinkWithSettings`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingUserRoutes_CreateSharedLinkWithSettingsAsync_1.htm) to create a new shared link or [`Sharing.ListSharedLinks`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Sharing_Routes_SharingUserRoutes_ListSharedLinksAsync_1.htm) to get existing links.

**Comment by cadilhac** [comment]
Thank you. Files.GetMetadata did the trick.
For the rest, I had already found Files.GetTemporaryLinkAsync and it works well. What is the difference between this and Sharing.CreateSharedLinkWithSettings?
Thanks.

**Comment by greg-db** [comment]
The `GetTemporaryLinkAsync` method gives you a temporary (4 hour) direct link.

The `CreateSharedLinkWithSettings` method gives you a shared link, from [this Dropbox shared link feature](https://www.dropbox.com/help/files-folders/view-only-access). These links point to a preview page by default (not directly to the file content) and are valid until revoked/deleted by the user or app.

**Comment by cadilhac** [comment]
ok thanks. Since I jsut want to download a file, GetTemporaryLinkAsync will be better suited here.
