### ISSUE TITLE
NULLReferenceException on ListFolderAsync

### ISSUE THREAD

**Issue by indian9pps** [dropbox/dropbox-sdk-dotnet#75]
Hi All I am developing an Xmarian APP and  when I try to traverse into subfolders as below, I keep running into NRE on following line of code

**File**: DropboxRequestHandler.cs
**Method called:** 
`var result = await CloudService.Instance.DropBoxService.Files.ListFolderAsync(arg);`
`var response = await this.getHttpClient(host).SendAsync(request, completionOption).ConfigureAwait(false);
`
This happens on both iOS and Android

**Directory Structure:** 1/2/3/4

What works is one level deep. i.e. Home/1

**Comment by greg-db** [comment]
Can you share the full stack trace/error output? Thanks in advance!

**Comment by indian9apps** [comment]
This is the ony error I see
`System.NullReferenceException: <Timeout exceeded getting exception details>`

**Comment by indian9pps** [comment]
Here is another exception I see
`at System.Net.Http.HttpClient.SendAsync (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption, System.Threading.CancellationToken cancellationToken) [0x00016] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.4/src/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:245 \n  at System.Net.Http.HttpClient.SendAsync (System.Net.Http.HttpRequestMessage request, System.Net.Http.HttpCompletionOption completionOption) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.6.1.4/src/mono/mcs/class/System.Net.Http/System.Net.Http/HttpClient.cs:231 \n  at Dropbox.Api.DropboxRequestHandler+<RequestJsonString>d__17.MoveNext () [0x003cd] in C:\\Users\\vivatury\\Downloads\\dropbox-sdk-dotnet-master\\dropbox-sdk-dotnet-master\\dropbox-sdk-dotnet\\Dropbox.Api\\DropboxRequestHandler.cs:475`

**Comment by qimingyuan** [comment]
Can you show us the code in FileView.xaml.cs where the exception is thrown?

**Comment by indian9pps** [comment]
here it is
`            if (args.SelectedItem.GetType() == typeof(FolderMetadata))
            {
                var item = args.SelectedItem as FolderMetadata;
                if (item != null && item.IsFolder)
                    await Navigation.PushAsync(new Views.DropBox.FilesView(item));
                else
                {
                    //await Navigation.PushAsync(new Views.Doc.DocumentViewer(item));
                }
            }
            else
            {
                // its a file
            }`

**Comment by qimingyuan** [comment]
Can you try adding a null check for args.SelectedItem? It doesn't seem the exception came from Dropbox SDK itself.

**Comment by indian9pps** [comment]
you are correct. Thanks for the help.
