### ISSUE TITLE
SimpleTest solution results in a 400 Error

### ISSUE THREAD

**Issue by Exho1** [dropbox/dropbox-sdk-dotnet#76]
I downloaded the project and ran Dropbox.Api.sln in Visual Studio 2017. There is a reference to the Dropbox.API version 4.7.0 for the solution as well, it did not work without it. I've attached my visual studio upgrade log down below, the universal demo is the only one with errors and I didn't use it anyways. Building SimpleTest only has a warning about "FilesUserRoutes.CreateFolderAsync(CreateFolderArg)" being obsolete. I replaced the commented out string with my API key and uncommented it and built the solution. The command line application then asks me if I wish to reset settings and regardless of a Y or N I end up on the Error (400) page. The client_id is my api key. 

I have not modified the project in any other way than mentioned above. Its directly from the Github. 

![dropbox1](https://user-images.githubusercontent.com/8472757/36637509-d82a6d3a-19a2-11e8-9c8a-428cc27e89ff.PNG)

![dropbox2](https://user-images.githubusercontent.com/8472757/36637511-dfb6790e-19a2-11e8-869d-277bd72cf946.PNG)

[UpgradeLog.zip](https://github.com/dropbox/dropbox-sdk-dotnet/files/1755662/UpgradeLog.zip)

**Comment by greg-db** [comment]
Can you give me a better idea of what the rest of the error string on the 400 page that you marked out is, after "Invalid client_id:"? The client ID value should just be the app key, which is generally just 15 characters long, but the marked out portion looks much longer. (Perhaps you put in your "access token" instead?)
