### ISSUE TITLE
Request Authorize Page, stuck on authorization

### ISSUE THREAD

**Issue by JatinRicky** [dropbox/dropbox-sdk-dotnet#79]
![wp_ss_20180423_0001](https://user-images.githubusercontent.com/32097959/39116574-6f70453e-4702-11e8-869f-615b77c0a20f.png)

I'm using WebAuthenticationBroker to authenticate with Dropbox cloud on Windows Phone 10 (Lumia 950, Version: 1709, OS build: 10.0.15254.1). But after entering the credentials on the screen a little progress bar appears on the bottom right of the screen and it keeps rotating forever. Using the same code in Windows Desktop app works fine and the result is returned by WebAuthenticationBroker. Problem is only occuring with phones only.
Please suggest a solution to this problem.

**Comment by greg-db** [comment]
@JatinRicky Thanks for the report! Do you know what browser and version this is using on this device? Also, does the Dropbox login work in the system browser itself on the same device?

**Comment by greg-db** [comment]
Thanks! It sounds like `WebAuthenticationBroker` is using IE 10 in particular, which unfortunately is not [supported by the Dropbox web site](https://www.dropbox.com/help/desktop-web/system-requirements#web), so we won't be able to offer a fix. Please switch to using the system browser instead.
