### ISSUE TITLE
AuthException returns JSON as exception message

### ISSUE THREAD

**Issue by JimiC** [dropbox/dropbox-sdk-dotnet#8]
This is more of an inconsistency bug rather than a functional bug.

Reproduction steps:
1. Authorize a user by getting an access token.
2. Unlink that user (makes the access token invalid)
3. Call any method (in my case it's GetCurrentAccountAsync)
4. An AuthException is thrown, message is in JSON format, instead of just a text description.

Although it's easy to parse the JSON and get the ".tag" value (that's what the exception returns as message), it would be nicer if there was a consistency with all other exception messages.

Suggestion:
The problem may lay in `DropboxRequestHandler.RequestJsonString` (line 400). The returned JSON doesn't contain the "error" key so `CheckForError` fails as the key is ".tag".

**Comment by qimingyuan** [comment]
This has been fixed in v2.3.2. Now AuthException is no longer thrown. Instead, the app should catch ApiException<AuthError> which contains deserialized object of the error json.

**Comment by qimingyuan** [comment]
Update: In order to retain the capability to distinguish api vs authentication related errors. We decided to keep AuthException class and add an extra ErrorResponse field of type AuthError so the client can handle it the same way as ApiException.
