### ISSUE TITLE
Warning in Visual Studio 2017 when referencing in .Net Standard Class Library

### ISSUE THREAD

**Issue by jculverwell** [dropbox/dropbox-sdk-dotnet#81]
I am getting this warning in Visual Studio.  This only seems to happen with the Dropbox nuget package and not any of the other third party libraries I use.  

```Package `Dropbox.Api 4.8.1 was restored using `.NetFramework, Version=v4.6.1` instead of the project target framework `.Net Standard,Version=v2.0`. This package may not be fully compatible with your project.```

Thanks

**Comment by Still34** [comment]
You can safely ignore this warning. The warning is simply telling you that it is using the new compatibility mode .NET Standard 2.0 introduced. That being said, #65 should resolve this.

**Comment by jculverwell** [comment]
Thank you

**Comment by jculverwell** [comment]
Thank you fixing this,  This is now resolved in the latest issue
