### ISSUE TITLE
how to work with multiple user accounts

### ISSUE THREAD

**Issue by KansaraMaulik** [dropbox/dropbox-sdk-dotnet#82]
What I want to know if suppose I am redirected to Dropbox Login page through WPF application and I successfully authenticated through credentials.
Now I want to change the user account. so is there any way like log out from the current user and again redirect to Dropbox login page for login using different user?

**Comment by greg-db** [comment]
Yes, you can handle multiple users in your app. Each Dropbox access token enables access to one Dropbox account, so you can store and switch between multiple access tokens as necessary.

I recommend trying out the SimpleBlogDemo example, which is a basic sample of allowing multiple users to use the Dropbox integration:

https://github.com/dropbox/dropbox-sdk-dotnet/tree/master/dropbox-sdk-dotnet/Examples/SimpleBlogDemo

**Comment by KansaraMaulik** [comment]
Yes that i have checked. But as per my knowledge, Dropbox allows about 500 users to access an application using same access token. what i want is to create one application on an account and then use access token of that application for more than one user account. so is there any feature available to achieve this?

**Comment by greg-db** [comment]
To clarify, a single access token always only enables access to a single user account (for user apps) or a single team (for team apps).

It sounds like you're referring to the limit on the number of accounts that can be linked to a particular app while that app is in development mode. You can get that limit removed by applying for and receiving "production" status. You can find more information on that here:

https://www.dropbox.com/developers/reference/developer-guide#production-approval
