### ISSUE TITLE
Error while downloading file

### ISSUE THREAD

**Issue by GitHubUniverse** [dropbox/dropbox-sdk-dotnet#86]
Hello.
I encountered an error when downloading large files.
File is not fully downloaded error occurs
```
'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.resources\v4.0_4.0.0.0b03f5f7f11d50a3a\System.Net.Http.resources.dll'. Module was built without symbols.
Exception thrown: 'System.IO.IOException' in System.Net.Http.dll
Exception thrown: 'System.IO.IOException' in mscorlib.dll
```

The impression is that the server is disconnected because the file transfer takes longer.

Using code:
```csharp
private async Task DownloadFile(DropboxClient client, string filePath, string localFilePath)
{
  using (var response = await client.Files.DownloadAsync(filePath))
  {
    using (var fileStream = File.Create(localFilePath))
    {
      response.GetContentAsStreamAsync().Result.CopyTo(fileStream);
    }
  }
}
```
Also an error occurs if you simultaneously download two or more files.

I hope for help in this matter.

**Comment by Still34** [comment]
That seems more like a .NET assembly issue  - perhaps try targeting a newer framework?

**Comment by GitHubUniverse** [comment]
> Thanks for the report. The code you shared looks correct though. I just tried this, and it worked fine for me.
> 
> Is that the full error/output you get? It doesn't seem to mention Dropbox.
> 
> Please share any/all relevant output. Also, how large are the files you are downloading?

This code works fine, but not for large files.

Error information (in Russian):
```
"Application1.vshost.exe" (CLR v4.0.30319: Application1.vshost.exe). Загружено "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\System.resources.dll". Сборка модуля выполнена без символов.
"Application1.vshost.exe" (CLR v4.0.30319: Application1.vshost.exe). Загружено "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.resources\v4.0_4.0.0.0_ru_b03f5f7f11d50a3a\System.Net.Http.resources.dll". Сборка модуля выполнена без символов.
Вызвано исключение: "System.IO.IOException" в System.Net.Http.dll
```
translate:
```
"Application1.vshost.exe" (CLR v4.0.30319: Application1.vshost.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.resources\v4.0_4.0.0.0_ru_b77a5c561934e089\System.resources.dll". The module was assembled without symbols.
"Application1.vshost.exe" (CLR v4.0.30319: Application1.vshost.exe). Loaded "C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.resources\v4.0_4.0.0.0_ru_b03f5f7f11d50a3a\System.Net.Http.resources.dll". The module was assembled without symbols.
An exception was thrown: "System.IO.IOException" in System.Net.Http.dll
```

The error occurs when I try to download a file of more than 220 MB
According to my observations, in different situations the download reaches 150-180 MB and is interrupted.
It is very likely that the server breaks the connection but I cannot confirm it.

Can I more accurately catch a error? I can connect Dropbox.Api with github by modifying the source code to get more accurate information about the error.

.NET Framework 4.5
.NET Framework 4.6.1
NuGet Dropbox.Api 4.8.1
NuGet Dropbox.Api 4.9.0

**Comment by GitHubUniverse** [comment]
> That seems more like a .NET assembly issue - perhaps try targeting a newer framework?

I am using Microsoft Visual Studio 2015

**Comment by Still34** [comment]
.NET assembly files are irrelevant from your IDE. That being said, it seems that you have tried different .NETFX versions as well, but it's still referencing 4.0 assemblies 🤔

**Comment by greg-db** [comment]
@GitHubUniverse Thanks for the additional output! It looks like this may be due to a timeout. Please try setting longer timeouts like the example here:

https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L68

**Comment by GitHubUniverse** [comment]
> @GitHubUniverse Thanks for the additional output! It looks like this may be due to a timeout. Please try setting longer timeouts like the example here:
> 
> https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L68

Thank you very much.

Now download works correctly. I can easily download files.

I added the reference to System.Net.Http.WebRequest, and made a change to the download method, adding from an [example:](https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L68)

```csharp
  var httpClient = new HttpClient(new WebRequestHandler { ReadWriteTimeout = 10 * 1000 })
  {
    Timeout = TimeSpan.FromMinutes(20)
  };

  var config = new DropboxClientConfig("SimpleTestApp")
  {
    HttpClient = httpClient
  };
```

```csharp
  DropboxClient dropboxClient = new DropboxClient(token, config)
```

Now your [example](https://www.dropboxforum.com/t5/API-Support-Feedback/How-to-get-Progress-Status-while-uploading-downloading-a-file-in/m-p/170685/highlight/true#M17203) is working correctly.
