### ISSUE TITLE
Add push notifications to track changes

### ISSUE THREAD

**Issue by mcdis** [dropbox/dropbox-sdk-dotnet#88]
Make allow to track changes.
The feature will make our app more reactive

**Comment by greg-db** [comment]
If you have a server-side app and you want to be notified of changes in the Dropbox accounts connected to your app, you can register for webhook notifications. You can find information on that here:

https://www.dropbox.com/developers/reference/webhooks

(Client-side applications can use [ListFolderLongpollAsync](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Files_Routes_FilesUserRoutes_ListFolderLongpollAsync_1.htm) to monitor for changes in a low-latency way.)
