### ISSUE TITLE
API method to revoke token

### ISSUE THREAD

**Issue by JimiC** [dropbox/dropbox-sdk-dotnet#9]
It would be extremely useful if you could provide an API method (endpoint) from where we can programmatically revoke a token.

**Comment by greg-db** [comment]
Thanks for the feedback!

**Comment by greg-db** [comment]
@JimiC This is available now via [`TokenRevokeAsync`](https://dropbox.github.io/dropbox-sdk-dotnet/html/M_Dropbox_Api_Auth_Routes_AuthRoutes_TokenRevokeAsync.htm). Hope this helps!
