### ISSUE TITLE
Basic App Authentication using the SDK

### ISSUE THREAD

**Issue by rachael-ross** [dropbox/dropbox-sdk-dotnet#93]
I've got a server-hosted .NET app that will need to connect to a single Dropbox account (on a schedule) and just overwrite a file there. In looking at the Dropbox documentation for authentication types, it states the following:

**App Authentication**

_**This type only uses the app's own app key and secret, and doesn't identify a specific user or team.** The app key and secret are transmitted in place of a username and password using "HTTP basic access authentication". Examples: When supplying the app key and secret for App Authentication, the app key and secret are given in place of the HTTP username and password, respectively. This can be done either as separate strings, as shown in the first two examples below, or as an base64-encoded Basic authorization string in the Authorization header, as in the third example below._

```
Example 1:
curl -X POST "https://api.dropbox.com/1/metadata/link" -u "<APP_KEY>:<APP_SECRET>" \
-d 
link="https://www.dropbox.com/sh/748egu7925f0gesq/AAHi80RJyhJFfkupnAU0wXuva?dl=0"

Example 2:
curl -X POST "https://<APP_KEY>:<APP_SECRET>@api.dropbox.com/1/metadata/link" \
-d 
link="https://www.dropbox.com/sh/748egu7925f0gesq/AAHi80RJyhJFfkupnAU0wXuva?dl=0"

Example 3:
curl -X POST "https://api.dropbox.com/1/metadata/link" \
--header "Authorization: Basic <base64(APP_KEY:APP_SECRET)>" \
-d "link=https://www.dropbox.com/sh/748egu7925f0gesq/AAHi80RJyhJFfkupnAU0wXuva?dl=0"
```

**Great! So I know it can be done without the whole OAuth authentication flow.....However, I can't seem to figure out how to perform App Authentication via the Dropbox.NET SDK by just supplying the AppKey and AppSecret.**

Anyone have a code example of how to perform Basic Auth rather than OAuth against Dropbox using this sdk?

**Comment by rachael-ross** [comment]
Hmmmm. Upon further reading, it appears that uploading documents to a folder isn't allowed with App Authentication.... am I understanding this correctly?

**Comment by greg-db** [comment]
[Cross-linking for reference: [https://stackoverflow.com/questions/54488855/dropbox-api-app-authentication-with-net-sdk](https://stackoverflow.com/questions/54488855/dropbox-api-app-authentication-with-net-sdk) ]

The "app authentication" style is only used for a few endpoints, which doesn't including the uploading endpoints. If you want to upload to Dropbox, you will need a user's access token, and use the "user authentication" style.

To upload via the .NET SDK, you should use the [one of the `Upload` methods](https://dropbox.github.io/dropbox-sdk-dotnet/html/Overload_Dropbox_Api_Files_Routes_FilesUserRoutes_UploadAsync.htm). There's [an example here](https://github.com/dropbox/dropbox-sdk-dotnet/blob/master/dropbox-sdk-dotnet/Examples/SimpleTest/Program.cs#L430).
