### ISSUE TITLE
Method Not Found: UploadAsync

### ISSUE THREAD

**Issue by 1michfan** [dropbox/dropbox-sdk-dotnet#94]
I am currently using version 4.9.0, and I was going to upgrade to the latest 4.9.3. When I upgraded, the UploadAsync method required a new parameter, strictConflict, which I added. Now when calling UploadAsync(path, mode, autorename, clientModified, mute, propertyGroups, strictConflict, body) I get the following exception:

> Method not found: 'System.Threading.Tasks.Task`1<Dropbox.Api.Files.FileMetadata> Dropbox.Api.Files.Routes.FilesUserRoutes.UploadAsync(System.String, Dropbox.Api.Files.WriteMode, Boolean, System.Nullable`1<System.DateTime>, Boolean, System.Collections.Generic.IEnumerable`1<Dropbox.Api.FileProperties.PropertyGroup>, Boolean, System.IO.Stream)'

I also tried using the other overload UploadAsync(commitInfo, body), but then I receive the following exception:

> Method not found: 'Void Dropbox.Api.Files.CommitInfo..ctor(System.String, Dropbox.Api.Files.WriteMode, Boolean, System.Nullable`1<System.DateTime>, Boolean, System.Collections.Generic.IEnumerable`1<Dropbox.Api.FileProperties.PropertyGroup>, Boolean)'.

As I stated above, this was working in version 4.9.0. 
This is the first time I have created an issue, please let me know if there is more info that I should be supplying.

**Comment by greg-db** [comment]
I just tried upgrading from 4.9.0 to 4.9.3 in a project, and I can't seem to reproduce this issue. Can you confirm that v4.9.3 of the library was successfully installed? Did you get any errors during the upgrade?

Otherwise, please let me know:
- what environment you're using; e.g., what version of Visual Studio, and NuGet
- the full code needed to reproduce the issue

**Comment by 1michfan** [comment]
Thank you for your reply.
The library was successfully installed and I didn't get any errors. To make sure, I downgraded back to 4.9.0, confirmed that the upload works, then upgraded to 4.9.3 again and it fails again.
Visual Studio version is 15.9.7. Nuget version is 4.6.0.
This is the function I am using:
```
Private Async Function UploadBackground(dropboxFolderPath As String, fileName As String, fileBytes As Byte(), overwriteFile As Boolean) As Task(Of FileMetadata)
        Dim dc As New DropboxClient(myAccessToken)
        Dim md As FileMetadata = Nothing
        Try
            Using strm As New MemoryStream(fileBytes)
                Dim mode As New WriteMode()
                If overwriteFile Then
                    mode = WriteMode.Overwrite.Instance
                Else
                    mode = WriteMode.Add.Instance
                End If
                md = Await dc.Files.UploadAsync(dropboxFolderPath & "/" & fileName, mode:=mode, autorename:=True, clientModified:=Nothing, mute:=False, propertyGroups:=Nothing, strictConflict:=False, body:=strm)
            End Using
        Catch ex As Exception
            'log error
        End Try
        Return md
End Function
```

**Comment by greg-db** [comment]
Thanks for the additional information. I just tried this code, upgrading from 4.9.0 to 4.93 with NuGet in Visual Studio and I'm unfortunately still not able to reproduce this issue though.

Would you be able to supply a small sample project that reproduces this so we can investigate? Apologies for the bother.

**Comment by 1michfan** [comment]
I created a new project to try to reproduce it, but it works as expected. I still can't get it to work in my project, so it must be something in my code.
Next time I will create a new project to reproduce it first. Thank you for your time.
