### ISSUE TITLE
UWP Release Build Failed with Dropbox.Api 4.9.4

### ISSUE THREAD

**Issue by ooikengsiang** [dropbox/dropbox-sdk-dotnet#98]
After updated to Dropbox.Api version 4.9.4 from version 4.9.3, UWP project release build failed with the following error:
`error : Method 'DropboxHelper.<List>d__13.MoveNext()' will always throw an exception due to the missing method 'FilesUserRoutes.ListFolderAsync(string, bool, bool, bool, bool, bool, Nullable<uint>, SharedLink, TemplateFilterBase)'. There may have been a missing assembly.`
This does not happen in debug build.

It seem like ListFolderAsync was removed by .Net native compiler. I tried to add the class name in Default.rd.xml, but the release build still failed with the same message.
`<Type Name="Dropbox.Api.Files.Routes.FilesUserRoutes" Dynamic="Required All" />`

Anyone have any better idea?

**Comment by TaylorKrusen** [comment]
Hi! That looks like a bug to me. I'd be happy to file it with engineering so we can get some help.

Would you mind providing some repro steps or sample code?

**Comment by ooikengsiang** [comment]
I was not able to duplicate the same problem in a newly created UWP project, but my existing project keep throwing missing method warning for that particular method only.
I think I will close this unless I can duplicate this in another project.
Sorry for the trouble.
